import { useMemo, useState } from "react";
import { ArrowLeft, Building2, ChevronLeft, Droplets, Mail, MapPin, Menu, Network, Phone, RadioTower, Route, ShieldCheck, X, Zap } from "lucide-react";
import { getMedia, loadCmsData, pageTemplates, type CmsData, type CmsPage, type CmsSection } from "@/lib/cmsStore";
import { brandAssets } from "@/lib/brandAssets";
import "../cmsClient.css";

const serviceCards = [["الطرق والأعمال المدنية", Route], ["شبكات المياه والري", Droplets], ["الصرف الصحي والمرافق", Network], ["الطاقة والاتصالات", Zap], ["الإنشاءات وتجهيز المواقع", Building2], ["المرافق وصيانة المواقع", ShieldCheck], ["الحلول التقنية", RadioTower]] as const;
const methodSteps = ["تحديد النطاق", "تجهيز الموقع", "تنفيذ مترابط", "تسليم واستمرارية"];
const previewPath = (slug: string) => `/preview/${slug === "/" ? "home" : slug.slice(1)}`;

function Section({ section, data, page }: { section: CmsSection; data: CmsData; page: CmsPage }) {
  const image = getMedia(data, section.imageId);
  if (section.type === "hero") return <section className="btuc-hero"><div className="btuc-shell btuc-hero-layout"><div className="btuc-hero-copy"><span className="btuc-eyebrow">{pageTemplates[page.template].eyebrow}</span><h1>{section.title}</h1><p>{section.description}</p><div className="btuc-hero-actions"><a href="#services">استكشف نطاقات العمل <ArrowLeft size={16} /></a><span><i /> تنفيذ متصل من البداية إلى الجاهزية</span></div></div><div className="btuc-hero-image" style={{ backgroundImage: `linear-gradient(145deg, rgba(5,28,47,.08), rgba(4,29,48,.72)), url(${image?.url ?? brandAssets.fieldCabinet})` }}><div><small>BTUC / {pageTemplates[page.template].label}</small><b>01</b><span>تنفيذ ببنية واضحة</span></div></div></div></section>;
  if (section.type === "signals") { const signals = section.description.split("·").map((item) => item.trim()).filter(Boolean); return <section className="btuc-signals"><div className="btuc-shell">{signals.map((item, index) => <div key={`${item}-${index}`}><b>{String(index + 1).padStart(2, "0")}</b><span>{item}</span></div>)}</div></section>; }
  if (section.type === "about") return <section className="btuc-about"><div className="btuc-shell btuc-about-layout"><div className="btuc-section-heading"><span className="btuc-eyebrow">منظور الشركة</span><h2>{section.title}</h2></div><div className="btuc-about-body"><p>{section.description}</p><div className="btuc-line" /><a href="#contact">ابدأ من نطاق مشروعك <ChevronLeft size={17} /></a></div>{image && <figure><img src={image.url} alt={image.alt} /><figcaption>تنسيق متكامل بين فرق الموقع والأنظمة</figcaption></figure>}</div></section>;
  if (section.type === "services") return <section className="btuc-services" id="services"><div className="btuc-shell"><header className="btuc-section-center"><span className="btuc-eyebrow">مجالات العمل</span><h2>{section.title}</h2><p>{section.description}</p></header><div className="btuc-service-grid">{serviceCards.map(([label, Icon], index) => <article key={label}><div><small>{String(index + 1).padStart(2, "0")}</small><Icon size={22} /></div><h3>{label}</h3><p>نطاق تنفيذي واضح يرتبط بمنظومة المرافق والبنية التحتية.</p><a href="#contact">اكتشف النطاق <ArrowLeft size={14} /></a></article>)}</div></div></section>;
  if (section.type === "method") return <section className="btuc-method"><div className="btuc-shell"><header><span className="btuc-eyebrow">منهجية التنفيذ</span><h2>{section.title}</h2><p>{section.description}</p></header><ol>{methodSteps.map((item, index) => <li key={item}><b>{String(index + 1).padStart(2, "0")}</b><div><h3>{item}</h3><p>قرار واضح ومتابعة منظمة ضمن مسار واحد يربط الموقع بالتسليم.</p></div></li>)}</ol></div></section>;
  if (section.type === "projects") { const gallery = [image, getMedia(data, "telecom-tower"), getMedia(data, "field-cabinet"), getMedia(data, "network-operations")].filter(Boolean); return <section className="btuc-projects"><div className="btuc-shell"><header className="btuc-projects-head"><div><span className="btuc-eyebrow">مشاريع مختارة</span><h2>{section.title}</h2></div><p>{section.description}</p></header><div className="btuc-project-grid">{gallery.map((item, index) => <figure key={`${item?.id}-${index}`}><img src={item?.url} alt={item?.alt} /><figcaption><small>نطاق {String(index + 1).padStart(2, "0")}</small><b>{["إدارة المرافق والموقع", "ربط الاتصالات والبنية", "تهيئة وتنفيذ مدني", "تكامل الأنظمة والتشغيل"][index]}</b></figcaption></figure>)}</div></div></section>; }
  return <section className="btuc-contact" id="contact"><div className="btuc-shell btuc-contact-layout"><div><span className="btuc-eyebrow">لنبدأ التعاون</span><h2>{section.title}</h2><p>{section.description}</p></div><div className="btuc-contact-links"><a href="tel:+966555199797"><Phone size={17} /><span><small>اتصال مباشر</small>+966 55 519 9797</span></a><a href="mailto:info@btuc.com.sa"><Mail size={17} /><span><small>البريد الإلكتروني</small>info@btuc.com.sa</span></a><a href="#top"><MapPin size={17} /><span><small>الموقع</small>الرياض، المملكة العربية السعودية</span></a></div></div></section>;
}

export default function CmsPagePreview() {
  const [data] = useState(() => loadCmsData());
  const [menuOpen, setMenuOpen] = useState(false);
  const page = useMemo(() => { const requested = window.location.pathname.replace(/^\/preview/, "") || "/"; const slug = requested === "/home" ? "/" : requested; return data.pages.find((item) => item.slug === slug) ?? data.pages.find((item) => item.slug === "/") ?? data.pages[0]; }, [data]);
  if (!page || page.status !== "منشورة") return <main className="btuc-not-found" dir="rtl"><h1>هذه الصفحة غير متاحة للزوار.</h1><a href="/admin">العودة إلى الإدارة</a></main>;
  const navPages = data.pages.filter((item) => item.status === "منشورة" && item.navVisible && item.slug !== "/");
  return <main className={`btuc-preview template-${page.template}`} dir="rtl" id="top"><header className="btuc-site-header"><div className="btuc-shell"><a className="btuc-preview-brand" href={previewPath("/")}><img src={brandAssets.logoMark} alt="شعار البرج الأزرق المتحدة" /><span>البرج الأزرق المتحدة<small>Blue Tower United Co.</small></span></a><button className="btuc-mobile-menu" onClick={() => setMenuOpen((open) => !open)} aria-label="فتح قائمة الصفحات">{menuOpen ? <X size={19} /> : <Menu size={20} />}</button><nav className={menuOpen ? "open" : ""}><a href={previewPath("/")}>الرئيسية</a>{navPages.map((item) => <a key={item.id} className={page.id === item.id ? "active" : ""} href={previewPath(item.slug)}>{item.title}</a>)}<a href="/admin" className="btuc-admin-link">الإدارة</a></nav></div></header>{page.sections.filter((item) => item.enabled).map((section) => <Section key={section.id} section={section} data={data} page={page} />)}<footer className="btuc-footer"><div className="btuc-shell"><span>البرج الأزرق المتحدة</span><small>بنية تحتية وإنشاءات وحلول متصلة للمشاريع والمرافق</small><a href="#top">العودة للأعلى</a></div></footer></main>;
}
