import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowUpLeft, Building2, Check, ChevronLeft, Cpu, Droplets, HardHat, Mail, MapPin, Menu, Network, Phone, RadioTower, Route, ShieldCheck, Sprout, X, Zap } from "lucide-react";
import { getMedia, loadCmsData, pageTemplates, type CmsData, type CmsPage, type CmsSection } from "@/lib/cmsStore";
import { brandAssets } from "@/lib/brandAssets";
import "../cmsClient.css";

const services = [["01", "الطرق والأعمال المدنية", Route], ["02", "شبكات المياه والري", Droplets], ["03", "الصرف الصحي والمرافق", Network], ["04", "الطاقة والاتصالات", Zap], ["05", "الإنشاءات وتجهيز المواقع", Building2], ["06", "المرافق وصيانة المواقع", Sprout], ["07", "الحلول التقنية المتكاملة", Cpu]] as const;
const stages = ["تحديد النطاق", "تجهيز الموقع", "تنفيذ مترابط", "تسليم واستمرارية"];
const previewPath = (slug: string) => `/preview/${slug === "/" ? "home" : slug.slice(1)}`;
const normalizeHref = (url?: string) => { if (!url) return undefined; const value = url.trim(); if (/^(#|https?:\/\/|mailto:|tel:)/i.test(value)) return value; if (value.startsWith("/")) return value.startsWith("/preview/") ? value : `/preview${value}`; return undefined; };
let currentRenderedSection: CmsSection | null = null;

function SectionCta({ section, className = "cms-text-link" }: { section: CmsSection | boolean; className?: string }) { const current: CmsSection | null = section === true ? currentRenderedSection : section === false ? null : section; const href = normalizeHref(current?.ctaUrl); return current && href && current.ctaLabel ? <a className={className} href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noreferrer" : undefined}>{current.ctaLabel}<ArrowLeft size={16} /></a> : null; }
function ImageCaption({ section, className = "cms-image-caption" }: { section: CmsSection | boolean; className?: string }) { const current: CmsSection | null = section === true ? currentRenderedSection : section === false ? null : section; return current?.caption ? <span className={className}>{current.caption}</span> : null; }
function mediaUrl(data: CmsData, id?: string, fallback = brandAssets.fieldCabinet) { return getMedia(data, id)?.url ?? fallback; }

function Brand() { return <a className="cms-brand-mark" href={previewPath("/")} aria-label="البرج الأزرق المتحدة"><img src={brandAssets.logoMark} alt="" /><span className="cms-brand-connector" /><span><b>البرج الأزرق المتحدة</b><small>للبنية التحتية والإنشاءات</small></span></a>; }

function Section({ section, data, page }: { section: CmsSection; data: CmsData; page: CmsPage }) {
  currentRenderedSection = section;
  const image = mediaUrl(data, section.imageId);
  if (section.type === "hero") return <section className="cms-hero-section"><div className="cms-gridline a" /><div className="cms-gridline b" /><div className="cms-hero-content"><div className="cms-eyebrow light"><span />{pageTemplates[page.template].eyebrow}</div><h1>{section.title}</h1><p>{section.description}</p><div className="cms-hero-actions"><SectionCta section={section} className="cms-button-primary" /><a className="cms-text-link light" href="#about">تعرّف على الصفحة <ChevronLeft size={17} /></a></div><div className="cms-hero-tags"><span>أعمال مدنية</span><span>شبكات ومرافق</span><span>حلول متكاملة</span></div></div><div className="cms-hero-visual"><img src={image} alt={getMedia(data, section.imageId)?.alt ?? "صورة مرتبطة بالقسم"} /><div className="cms-hero-schematic"><i className="arc one" /><i className="arc two" /><i className="route one" /><i className="route two" /><b className="node one" /><b className="node two" /><small className="label one">01 / المدنية</small><small className="label two">02 / المرافق</small></div>{section.captionPosition === "above" && <ImageCaption section className="cms-image-caption above" />}<div className="cms-survey-card"><i /><div><b>نطاق متصل</b><small>تنفيذ يربط التخصصات</small></div></div>{section.captionPosition !== "above" && <ImageCaption section />}</div><div className="cms-hero-footnote">الرياض · المملكة العربية السعودية</div></section>;
  if (section.type === "signals") { const parts = section.description.split("·").map((part) => part.trim()).filter(Boolean); return <section className="cms-signal-bar"><div>{parts.slice(0, 3).map((part, index) => <article key={`${part}-${index}`}><b>{["A", "B", "C"][index]}</b><p>{part}</p></article>)}</div></section>; }
  if (section.type === "about") return <section id="about" className="cms-about-section cms-wrap"><div className="cms-section-kicker"><span>01</span> تعريف بالشركة</div><div className="cms-about-layout"><div><div className="cms-eyebrow"><span />من رؤية ميدانية إلى منظومة عمل</div><h2>{section.title}</h2></div><div className="cms-about-copy"><p>{section.description}</p><SectionCta section /></div></div><figure className="cms-about-image"><img src={image} alt={getMedia(data, section.imageId)?.alt ?? "صورة الشركة"} />{section.captionPosition === "above" && <ImageCaption section className="cms-image-caption above" />}{section.captionPosition !== "above" && <ImageCaption section />}</figure></section>;
  if (section.type === "principles") { const items = section.description.split("·").map((item) => item.trim()).filter(Boolean); return <section className="cms-principles cms-wrap"><header><div className="cms-section-kicker"><span>02</span> مبادئ التنفيذ</div><h2>{section.title}</h2></header><div>{items.slice(0, 3).map((item, index) => { const Icon = [ShieldCheck, Network, HardHat][index]; return <article key={item}><Icon size={22} /><b>{["وضوح تنفيذي", "تكامل تخصصي", "جاهزية ميدانية"][index]}</b><p>{item}</p></article>; })}</div><SectionCta section /></section>; }
  if (section.type === "services") return <section id="services" className="cms-services-section"><div className="cms-wrap"><div className="cms-section-kicker dark"><span>03</span> مجالات العمل</div><div className="cms-services-heading"><h2>{section.title}</h2><p>{section.description}</p></div></div><div className="cms-service-rail">{services.map(([number, title, Icon], index) => <article key={title}><div className="cms-service-image"><img src={[image, brandAssets.networkOperations, brandAssets.telecomTower, brandAssets.fieldCabinet][index % 4] ?? image} alt="" /><span><small>مسار</small>{number}</span></div><div className="cms-service-body"><i><Icon size={20} /></i><small>نطاق تنفيذ مترابط</small><h3>{title}</h3><p>مسار عملي يتصل بمنظومة الموقع والمرافق والجاهزية التشغيلية للمشروع.</p><a href="#contact">ناقش نطاق التنفيذ <ArrowLeft size={15} /></a></div></article>)}</div><div className="cms-services-cta cms-wrap"><SectionCta section className="cms-text-link light" /></div></section>;
  if (section.type === "method") return <section id="method" className="cms-method-section cms-wrap"><div className="cms-method-lead"><div><div className="cms-section-kicker"><span>04</span> طريقة العمل</div><h2>{section.title}</h2></div><p>{section.description}</p></div><div className="cms-stages">{stages.map((stage, index) => <article key={stage}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{stage}</h3><p>خطوة واضحة تتصل بما قبلها وما بعدها للوصول إلى جاهزية منظمة.</p></div></article>)}</div><figure className="cms-method-image"><img src={image} alt={getMedia(data, section.imageId)?.alt ?? "منهجية تنفيذ"} /><figcaption><span>منهجية مترابطة</span><b>{section.caption || "كل مرحلة تمهّد لما بعدها."}</b></figcaption></figure><SectionCta section /></section>;
  if (section.type === "metrics") { const metrics = section.description.split("·").map((item) => item.trim()).filter(Boolean); return <section className="cms-metrics"><div className="cms-wrap"><header><div className="cms-section-kicker"><span>05</span> مؤشرات التنفيذ</div><h2>{section.title}</h2></header><div>{metrics.map((metric, index) => <article key={metric}><b>{String(index + 1).padStart(2, "0")}</b><span>{metric}</span></article>)}</div></div></section>; }
  if (section.type === "projects") { const gallery = [image, brandAssets.telecomTower, brandAssets.fieldCabinet, brandAssets.networkOperations]; return <section id="projects" className="cms-projects-section cms-wrap"><div className="cms-projects-head"><div><div className="cms-section-kicker"><span>06</span> سجل المشاريع</div><h2>{section.title}</h2></div><p>{section.description}</p></div><div className="cms-project-grid">{gallery.map((src, index) => <figure key={`${src}-${index}`}><img src={src} alt="صورة من أعمال BTUC" /><figcaption><small>نطاق {String(index + 1).padStart(2, "0")}</small><b>{["إدارة المرافق والموقع", "ربط الاتصالات والبنية", "تهيئة وتنفيذ مدني", "تكامل الأنظمة والتشغيل"][index]}</b>{index === 0 && <SectionCta section className="cms-project-link" />}</figcaption></figure>)}</div></section>; }
  if (section.type === "gallery") return <section className="cms-gallery-section"><div className="cms-wrap"><div className="cms-gallery-heading"><div className="cms-section-kicker"><span>07</span> توثيق بصري</div><h2>{section.title}</h2><p>{section.description}</p></div><div className="cms-gallery-grid">{[image, brandAssets.networkOperations, brandAssets.telecomTower, brandAssets.fieldCabinet].map((src, index) => <figure key={`${src}-${index}`}><img src={src} alt="صورة من نطاق العمل" />{index === 0 && <ImageCaption section />}</figure>)}</div><SectionCta section /></div></section>;
  if (section.type === "faq") { const questions = section.description.split("·").map((item) => item.trim()).filter(Boolean); return <section className="cms-faq-section cms-wrap"><div className="cms-faq-title"><div className="cms-section-kicker"><span>08</span> أسئلة شائعة</div><h2>{section.title}</h2><SectionCta section /></div><div>{questions.map((question, index) => <details key={question} open={index === 0}><summary>{question}<ChevronLeft size={17} /></summary><p>يوفر فريق BTUC بداية عملية لتحديد المسار الأنسب، ثم ينسّق نطاقات الأعمال ذات الصلة بما يخدم جاهزية التنفيذ.</p></details>)}</div></section>; }
  if (section.type === "cta") return <section className="cms-cta-section"><div className="cms-wrap"><div><div className="cms-eyebrow light"><span />خطوة البداية</div><h2>{section.title}</h2><p>{section.description}</p><SectionCta section className="cms-button-primary" /></div><figure><img src={image} alt={getMedia(data, section.imageId)?.alt ?? "صورة مرتبطة بالدعوة"} />{section.caption && <ImageCaption section />}</figure></div></section>;
  return <section id="contact" className="cms-contact-section"><div className="cms-contact-mapline" /><div className="cms-wrap cms-contact-inner"><div><div className="cms-eyebrow light"><span />لنبدأ من احتياجك</div><h2>{section.title}</h2><p>{section.description}</p><SectionCta section className="cms-text-link light" /></div><div className="cms-contact-card"><a href="tel:+966555199797"><i><Phone size={18} /></i><div><small>اتصال مباشر</small><b dir="ltr">+966 55 519 9797</b></div><ArrowUpLeft size={17} /></a><a href="mailto:info@btuc.com.sa"><i><Mail size={18} /></i><div><small>البريد الإلكتروني</small><b>info@btuc.com.sa</b></div><ArrowUpLeft size={17} /></a><a href="#top"><i><MapPin size={18} /></i><div><small>موقعنا</small><b>الرياض، المملكة العربية السعودية</b></div><ArrowUpLeft size={17} /></a></div></div></section>;
}

export default function CmsPagePreview() {
  const [data] = useState(() => loadCmsData()); const [menuOpen, setMenuOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 16); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  const page = useMemo(() => { const requested = window.location.pathname.replace(/^\/preview/, "") || "/"; const slug = requested === "/home" ? "/" : requested; return data.pages.find((item) => item.slug === slug) ?? data.pages.find((item) => item.slug === "/") ?? data.pages[0]; }, [data]);
  if (!page || page.status !== "منشورة") return <main className="cms-not-found" dir="rtl"><h1>هذه الصفحة غير متاحة للزوار.</h1><a href="/admin">العودة إلى الإدارة</a></main>;
  const navPages = data.pages.filter((item) => item.status === "منشورة" && item.navVisible && item.slug !== "/");
  return <main id="top" className="cms-client-shell" dir="rtl"><header className={`cms-site-header ${scrolled ? "is-scrolled" : ""}`}><div className="cms-header-inner"><Brand /><nav className="cms-desktop-nav"><a href={previewPath("/")}>الرئيسية</a>{navPages.map((item) => <a className={item.id === page.id ? "active" : ""} key={item.id} href={previewPath(item.slug)}>{item.title}</a>)}</nav><a className="cms-header-cta" href="#contact">اطلب تواصلاً<ArrowUpLeft size={16} /></a><button className="cms-menu-button" onClick={() => setMenuOpen((open) => !open)} aria-label="فتح القائمة">{menuOpen ? <X size={22} /> : <Menu size={23} />}</button></div><div className={`cms-mobile-panel ${menuOpen ? "is-open" : ""}`}><nav><a href={previewPath("/")}>الرئيسية</a>{navPages.map((item) => <a key={item.id} href={previewPath(item.slug)}>{item.title}</a>)}<a href="/admin">لوحة الإدارة</a></nav></div></header>{page.sections.filter((section) => section.enabled).map((section) => <Section key={section.id} section={section} data={data} page={page} />)}<footer className="cms-site-footer"><div className="cms-footer-main"><Brand /><p>شركة البرج الأزرق المتحدة<br />الرياض، المملكة العربية السعودية</p><a href="#top">العودة إلى الأعلى <ChevronLeft size={16} /></a></div><div className="cms-footer-bottom"><span>© {new Date().getFullYear()} شركة البرج الأزرق المتحدة</span><span>إنشاءات · بنية تحتية · حلول متكاملة</span></div></footer></main>;
}
